template-file-path: template.yaml
parameters:
  VpcCidr: 10.0.0.0/16
  PublicSubnetCidr1: 10.0.1.0/24
  PublicSubnetCidr2: 10.0.2.0/24
  PrivateSubnetCidr1: 10.0.3.0/24
  PrivateSubnetCidr2: 10.0.4.0/24
  ProjectTag: week5
  CPUPolicyTargetValue: 50
  ContainerName: GalleryAppContainer
  ECSServiceName: gallery-app-task-definition-service
  ClusterName: GalleryAppCluster
  TaskDefinitionName: GalleryAppTask
  ECSTaskExecutionRoleName: galleryAppTaskExecutionRole
  ECSTaskRoleName: galleryAppTaskRole
  ECRRepoName: week5/mini-project-repo
  ImageTag: 734661c71932256aaef6c73cc60747c9043dd9b6

tags: {}
