template-file-path: template.yaml
parameters:
  VpcCidr: 10.0.0.0/16
  PublicSubnetCidr1: 10.0.1.0/24
  PublicSubnetCidr2: 10.0.2.0/24
  PrivateSubnetCidr1: 10.0.3.0/24
  PrivateSubnetCidr2: 10.0.4.0/24
  ProjectTag: week5
  CPUPolicyTargetValue: 50
  ContainerImageURI: 985539763589.dkr.ecr.eu-central-1.amazonaws.com/week5/mini-project-repo:734661c71932256aaef6c73cc60747c9043dd9b6
  ContainerName: GalleryAppContainer
  ServiceName: GalleryAppService
  ClusterName: GalleryAppCluster
  TaskDefinitionName: GalleryAppTask
  ECSTaskExecutionRoleName: galleryAppTaskExecutionRole
  ECSTaskRoleName: galleryAppTaskRole

tags: {}
